### ISSUE TITLE
原来的相册模块为什么给取消掉了

### ISSUE THREAD

**Issue by chwl66** [HaoOuBa/Joe#14]
不知道从哪个版本开始，相册模块取消了，图片多了真的不好看！

**Comment by HaoOuBa** [comment]
你好，那些功能，在后期会加上的

**Comment by chwl66** [comment]
> 你好，那些功能，在后期会加上的

现在我用回了老版本，等啥时候加上去我再用新版本吧！现在我的图片看着真的别扭！
