### ISSUE TITLE
反馈与建议

### ISSUE THREAD

**Issue by PluginsKers** [HaoOuBa/Joe#15]
## 展望未来

- 不在首页显示所设置的标签下的文章（或者单只是文章）
- 每页显示文章可以跟随Typecho的设置
- 可以实现一些高级的`markdown`语法，比如：上角标，次方，微积分等符号
- 支持多种颜色的`joe-card`

这里感谢Joe大佬给我们带来的这款好用的主题！！！！！！！！！！

## BUG反馈

有BUG？不阔能的。

**Comment by PluginsKers** [comment]
BUG

- 修改为原版编辑器（包括新版），视频什么的按钮没了嘛。

**Comment by HaoOuBa** [comment]
正在重构编辑器

**Comment by ovoxinsong** [comment]
大佬你群号~可以发一下吗，我被T了？

**Comment by HaoOuBa** [comment]
> 大佬你群号~可以发一下吗，我被T了？

198963776

**Comment by yang9w** [comment]
大佬。你的苹果CMS页面的API接口可以多次使用吗？多个页面解析多个网站的API。页面可以设置密码。

**Comment by HaoOuBa** [comment]
> 页

不可以的

**Comment by PluginsKers** [comment]
......
