### ISSUE TITLE
想问问这个主题用的字体是什么~太好看惹！！！

### ISSUE THREAD

**Issue by ovoxinsong** [HaoOuBa/Joe#16]
想问问这个主题用的字体是什么~太好看惹！！！

**Comment by HaoOuBa** [comment]
没用字体，默认字体，你看错了吧。。

**Comment by ovoxinsong** [comment]
> 没用字体，预设字体，你看错了吧。。

傻了= =好吧，。是那个博主自定义了。我去问问他，谢谢！我给你看看这个字体，https://www.52craft.cc/

**Comment by HaoOuBa** [comment]
主题后台设置可以自定义字体，他这个是使用了自定义字体

**Comment by ovoxinsong** [comment]
> 主题后台设置可以自定义字体，他这个是使用了自定义字体

看到啦~感谢！
