### ISSUE TITLE
浏览器地址栏提示不安全

### ISSUE THREAD

**Issue by 100234** [HaoOuBa/Joe#19]
看了一下源码，里面xmlns="http://www.w3.org/2000/svg"是HTTP协议，没有加密，大佬能不能整体改一下，提示不安全有点怪怪的，感谢

**Comment by HaoOuBa** [comment]
> 看了一下源码，里面xmlns="[http://www.w3.org/2000/svg"是HTTP协议，没有加密，大佬能不能整体改一下，提示不安全有点怪怪的，感谢](http://www.w3.org/2000/svg%22%E6%98%AFHTTP%E5%8D%8F%E8%AE%AE%EF%BC%8C%E6%B2%A1%E6%9C%89%E5%8A%A0%E5%AF%86%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E4%B8%8D%E8%83%BD%E6%95%B4%E4%BD%93%E6%94%B9%E4%B8%80%E4%B8%8B%EF%BC%8C%E6%8F%90%E7%A4%BA%E4%B8%8D%E5%AE%89%E5%85%A8%E6%9C%89%E7%82%B9%E6%80%AA%E6%80%AA%E7%9A%84%EF%BC%8C%E6%84%9F%E8%B0%A2)

你好，HTTPS协议提示这个与您的图片、友链有关、代码内的svg xmlns为固定写法，与您的https没有关系

**Comment by 100234** [comment]
> > 看了一下源码，里面xmlns="[http://www.w3.org/2000/svg"是HTTP协议，没有加密，大佬能不能整体改一下，提示不安全有点怪怪的，感谢](http://www.w3.org/2000/svg%22%E6%98%AFHTTP%E5%8D%8F%E8%AE%AE%EF%BC%8C%E6%B2%A1%E6%9C%89%E5%8A%A0%E5%AF%86%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E4%B8%8D%E8%83%BD%E6%95%B4%E4%BD%93%E6%94%B9%E4%B8%80%E4%B8%8B%EF%BC%8C%E6%8F%90%E7%A4%BA%E4%B8%8D%E5%AE%89%E5%85%A8%E6%9C%89%E7%82%B9%E6%80%AA%E6%80%AA%E7%9A%84%EF%BC%8C%E6%84%9F%E8%B0%A2)
> 
> 你好，HTTPS协议提示这个与您的图片、友链有关、代码内的svg xmlns为固定写法，与您的https没有关系

多谢，查了一下，确实是我从微博复制来的图片链接是http
