### ISSUE TITLE
文字跑出边界了

### ISSUE THREAD

**Issue by sunlight2728** [HaoOuBa/Joe#23]
<img width="1421" alt="截屏2021-04-23 下午7 43 34" src="https://user-images.githubusercontent.com/10278159/115866507-54bc9380-a46c-11eb-8f95-7a30aeb30a34.png">

文字跑出边界了

**Comment by HaoOuBa** [comment]
开头不要用4个空格。4个空格在markdown中属于代码块。使用编辑器自带的缩进功能

**Comment by sunlight2728** [comment]
1
