### ISSUE TITLE
加密文章输入密码都是错误，默认主题就正常了

### ISSUE THREAD

**Issue by xu1024io** [HaoOuBa/Joe#37]
Typecho 版本 1.2 (18.10.23)，Joe版本 7.2.9

加密文章输入密码都是错误，默认主题就正常了

![image](https://user-images.githubusercontent.com/86138996/122660537-e28ad580-d1b4-11eb-9dc5-2098668b23aa.png)
![image](https://user-images.githubusercontent.com/86138996/122660540-e7e82000-d1b4-11eb-99f7-07a87c22006a.png)

**Comment by HaoOuBa** [comment]
将在7.3.0版本解决
