### ISSUE TITLE
正文作者的小头像无法更改

### ISSUE THREAD

**Issue by jglicat** [HaoOuBa/Joe#70]
![QQ图片20211214152301](https://user-images.githubusercontent.com/44884897/145951715-46395c2b-4bc4-4f63-ae17-5eabe703f4cc.png)
在主题设置里没找到相关选项，每次都是默认头像

**Comment by willhenryhoo** [comment]
这个也希望应用作者的头像，不需要单独设置。

**Comment by cnhongv** [comment]
修改主题`/public`目录的`batten.php`第21行
![image](https://user-images.githubusercontent.com/19757650/168417886-42171211-838f-4d85-a88a-9540ed1d3ec6.png)
将` _getAvatarByMail($this->author->mail)`修改为`$this->options->JAside_Author_Avatar ? $this->options->JAside_Author_Avatar() : _getAvatarByMail($this->authorId ? $this->author->mail : $this->user->mail);`
![image](https://user-images.githubusercontent.com/19757650/168417961-64154d7c-c8c7-4e4e-a362-201d2ec1be07.png)
@willhenryhoo @jglicat

**Comment by zwtduserid** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。
