### ISSUE TITLE
BUG: 代码块如果长度过长会凸出文章边界

### ISSUE THREAD

**Issue by hapke24** [HaoOuBa/Joe#81]
## BUG
- 如图：
![image](https://user-images.githubusercontent.com/49407099/159120663-9970063c-ced8-4480-bb01-d5a6a8f2cad5.png)
## 期望结果
- 代码过长时增加横向滚轮

**Comment by Roookie-langp** [comment]
你给代码块指定一种语言就行了，随便java啥的都行
