### ISSUE TITLE
[Typecho1.2.0] 更新后Joe暂时不支持新版本

### ISSUE THREAD

**Issue by i-Yirannn** [HaoOuBa/Joe#82]
不知道作者大大有没有适配1.2.0的计划, joe主题在1.2.0上主页不能正常显示post, 显示为加载中.
我怀疑是一些API更新并尝试修复这些问题, 但是没能成功

**Comment by i-Yirannn** [comment]
最难受的是Typecho的1.2似乎还动了数据库, 回滚版本也会失败

**Comment by Asyncload** [comment]
我就是用的Typecho1.2.0

**Comment by i-Yirannn** [comment]
> 我就是用的Typecho1.2.0

请问您是直接1.2.0还是从1.1升级的, 您用着没有任何问题么?
我是按照官网要求把相应文件\文件夹替换(也就是除了usr之外的), 之后joe就不能用了

**Comment by i-Yirannn** [comment]
感谢提醒..我把主题重新安装就好了
